### ISSUE TITLE
Come up with new name for this project

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/glassfish-concurro#49]
"Concurrency RI" is the kind of name that was agreed to not to be used anymore by the former RI projects. This is to create a level playing field where all implementations are equal in that context.

See for example the project names created for the EL RI (ExpressLy), the JSP RI (WaSP), the Mail RI (Angus), etc.

**Comment by arjantijms** [comment]
@m0mus @smillidge @edbratt @frowe @jgallimore 

What about "SynchronicityX" any takers for that?

**Comment by waynebeaton** [comment]
Expectation management: there's lots of hits on "Synchronicity" in the USPTO database. We haven't looked particularly hard, so that doesn't necessarily mean we can't use the name for a project, but it doesn't look good.

In any case, the project name cannot infringe on a trademark that is held by somebody else. I recommend that you come up with at least a couple of alternatives.

Sorry to be the King of Pain on this one.

**Comment by arjantijms** [comment]
@waynebeaton thanks, I know about the process and various other names for previous projects here could not be accepted for that very reason. I added the X behind the name for specifically that reason, but it may not be enough indeed.

Some alternative suggestions then (hope others can chime in as well:

* Concurrō (latin for "at the same time)
* SynchroWeaver
* ThreadOrchestra
* Träid (old Frisian for Thread)
* ThreadLy
* Simultano

**Comment by arjantijms** [comment]
If there are no other suggestions or votes, I think Concurrō is the clear winner. Thanks everyone!

**Comment by arjantijms** [comment]
@waynebeaton can we go ahead and rename the repo to "concurro" (stylised in the description as Concurrō)? Or should we move (restructure) the project first?

cc @ivargrimstad

**Comment by waynebeaton** [comment]
My apologies for the delay. While we do try to monitor channels where we are copied, we're not always successful. Your best bet for these sorts of questions is to send a note to emo@eclipse-foundation.org.

I assure you that the tardiness of my response has nothing to do with my disappointment that nobody responded to my "King of Pain" reference.

Anyway... as I said earlier, we need to take care to not infringe on trademarks held by others. Please engage with the EMO to set up a restructuring review. The EMO will engage with our trademarks team to confirm that we can use the name and then coordinate with the IT team to update the name in all the places that it's used.

Note that restructuring reviews generally include a week of "community review", but -- since you've basically already done this part with this issue -- in this case it's more about tracking and implementing the change.

**Comment by aubi** [comment]
@arjantijms Can we close this issue as the repo is renamed?

**Comment by arjantijms** [comment]
Yes, absolutely!
